=== tahalekhlaikh/projet_XML_LEKHLAIKH_M-BARKI/evenements_par_mois.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="mois_annee">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="evenement"/>
      </xs:sequence>
      <xs:attributeGroup ref="attlist.mois_annee"/>
    </xs:complexType>
  </xs:element>
  <xs:attributeGroup name="attlist.mois_annee">
    <xs:attribute name="mois" use="required"/>
  </xs:attributeGroup>
  <xs:element name="evenement">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="icon"/>
        <xs:element ref="type"/>
        <xs:element ref="titre"/>
        <xs:element ref="date"/>
        <xs:element ref="heure"/>
        <xs:element ref="lieu"/>
        <xs:element ref="organisateur"/>
        <xs:element ref="descriptif"/>
        <xs:element maxOccurs="unbounded" ref="animateurs"/>
      </xs:sequence>
      <xs:attributeGroup ref="attlist.evenement"/>
    </xs:complexType>
  </xs:element>
  <xs:attributeGroup name="attlist.evenement">
    <xs:attribute name="jour" use="required"/>
  </xs:attributeGroup>
  <xs:element name="icon" type="xs:string"/>
  <xs:element name="type" type="xs:string"/>
  <xs:element name="titre" type="xs:string"/>
  <xs:element name="date" type="xs:string"/>
  <xs:element name="heure" type="xs:string"/>
  <xs:element name="lieu" type="xs:string"/>
  <xs:element name="organisateur" type="xs:string"/>
  <xs:element name="descriptif" type="xs:string"/>
  <xs:element name="animateurs">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="nom_prenom"/>
        <xs:element ref="fonction"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="nom_prenom" type="xs:string"/>
  <xs:element name="fonction" type="xs:string"/>
</xs:schema>

=== tahalekhlaikh/projet_XML_LEKHLAIKH_M-BARKI/mars2020.xml
<?xml version ="1.0" ?>
<?xml-stylesheet type ="text/xsl" href ="evenements_par_mois.xsl" ?>

    <mois_annee mois="Mars 2020" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="evenements_par_mois.xsd">
        <evenement jour="22">
             <icon>images/icon/SOCIAL-BUSINESS-2-670x474.jpg</icon>
             <type>Conférence débat</type>
             <titre>Social business : comment changer d’échelle ?</titre>
             <date>Mardi 22 Mars 2020</date>
             <heure>17h00 à 19h30</heure>
             <lieu>Salle polyvalente</lieu>
             <organisateur>EMI-Business</organisateur>
             <descriptif>Lutter contre la malnutrition infantile chronique à Madagascar, promouvoir l’accès de tous à une énergie propre et économique au Cambodge, concilier économie circulaire et traitement des déchets en Argentine… tout en étant rentable : tels sont les paris des social business. Ces initiatives se multiplient et suscitent l’intérêt d’un nombre croissant d’acteurs, dans la sphère politique comme dans celle des bailleurs. Pourquoi ? Car ces initiatives convainquent par leur capacité à répondre à des problématiques sociétales (sociales et environnementales) et ouvrent la voie à une économie réellement inclusive.</descriptif>
             <animateurs>
                 <nom_prenom>David AUERBACH</nom_prenom>
                 <fonction>co-fondateur de Sanergy
                 </fonction>
             </animateurs>
             <animateurs>
                 <nom_prenom>Emmanuel BEAU</nom_prenom>
                 <fonction>directeur d’investissement pour le fonds Energy Access Ventures (EAV)
                 </fonction>
             </animateurs>
			 <animateurs>
                 <nom_prenom>Jean Gabriel DAYRE</nom_prenom>
                 <fonction>chargé d’affaires senior à Proparco
                 </fonction>
             </animateurs>
        </evenement>
        <evenement jour="8">
             <icon>images/icon/unicef-enfants_th_128.jpg</icon>
             <type>Séminaire</type>
             <titre>Genre et protection sociale</titre>
             <date>Mardi 8 Mars 2020</date>
             <heure>14h à 18h</heure>
             <lieu>Grand amphi</lieu>
             <organisateur>Club Social</organisateur>
             <descriptif>Ce séminaire répond au double objectif d’améliorer notre compréhension des enjeux de genre dans les différents domaines de la protection sociale (santé, emploi ou petite enfance) et d'améliorer ensuite l'intégration de ces enjeux dans les projets portés par l’AFD, en partageant les données et leçons apprises des partenaires impliqués dans le domaine de la protection sociale.</descriptif>
             <animateurs>
                 <nom_prenom>Jean-Noël Roulleau</nom_prenom>
                 <fonction> responsable de la Division Appui Environnemental et Social à l’AFD
                 </fonction>
             </animateurs>
             <animateurs>
                 <nom_prenom>Maya Stern-Plaza</nom_prenom>
                 <fonction>spécialiste principale protection sociale au BIT
                 </fonction>
             </animateurs>
			 <animateurs>
                 <nom_prenom>Jean-Noël Roulleau</nom_prenom>
                 <fonction> responsable de la Division Appui Environnemental et Social à l’AFD
                 </fonction>
             </animateurs>
             <animateurs>
                 <nom_prenom>Carine Clert</nom_prenom>
                 <fonction>spécialiste principale protection sociale à la Banque mondiale
                 </fonction>
             </animateurs>
			 <animateurs>
                 <nom_prenom>Marie-Pierre Nicollet</nom_prenom>
                 <fonction>directrice du département Développement humain de l’AFD
                 </fonction>
             </animateurs>
        </evenement>
    </mois_annee>

=== tahalekhlaikh/projet_XML_LEKHLAIKH_M-BARKI/avril2020.xml
<?xml version ="1.0" ?>
<?xml-stylesheet type ="text/xsl" href ="evenements_par_mois.xsl" ?>

    <mois_annee mois="Avril 2020" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="evenements_par_mois.xsd">
        <evenement jour="12">
             <icon>images/icon/petrole_th_128.jpg</icon>
             <type>Conférence débat</type>
             <titre>Un pétrole à moins de 30$ le baril : quelles conséquences pour le développement ?</titre>
             <date>Mardi 12 avril 2020</date>
             <heure>17h00</heure>
             <lieu>Salle polyvalente</lieu>
             <organisateur>EMI-Economie</organisateur>
             <descriptif>Depuis le milieu de l’année 2014, le panorama énergétique mondial a changé. Le prix du pétrole semble durablement bas, les surcapacités de production s’étendent, et les analystes ne semblent pas encore entrevoir de fléchissement de la tendance. Un cours bas du pétrole a des conséquences dramatiques pour les pays exportateurs les plus fragiles en termes de rentrées fiscales et de risque souverain. Il influe aussi sur les stratégies des pays importateurs, en réorientant potentiellement les stratégies de diversification du mix énergétique et retardant les politiques de réduction des émissions de gaz à effet de serre.
             </descriptif>
             <animateurs>
                 <nom_prenom>Fréderic Baule</nom_prenom>
                 <fonction>Consultant chez Cédrac Conseil et ENERDATA, professeur associé à IFP Training, ancien Vice President Market Risk Management chez TOTAL Marketing et Services.
                 </fonction>
             </animateurs>
             <animateurs>
                 <nom_prenom>Olivier Rech</nom_prenom>
                 <fonction>Economiste de l’énergie chez Beyond Ratings, ancien analyste chez Energy Fund Advisors, Carbon4 et au bureau du chef économiste de l’AIE.
                 </fonction>
             </animateurs>
        </evenement>
        <evenement jour="11">
             <icon>images/icon/Nuage GIRE_15-1_th_128.jpg</icon>
             <type>Séminaire</type>
             <titre>Acteurs de l’eau et du climat : concilions nos agendas ! Séminaire 3 – L’influence des concepts et des instruments</titre>
             <date>Lundi 11 avril 2020</date>
             <heure>9h30</heure>
             <lieu>Grand amphi</lieu>
             <organisateur>Club d'environnement</organisateur>
             <descriptif>Bassin versant, gestion intégrée des ressources, gouvernance de l’eau… L’ambition de « gérer l’eau douce » a nourri, au fil des précédentes décennies, de nombreux concepts et représentations pour mobiliser la ressource. De nouveaux cadres de pensée et d’action émergent : eau-territoire, eau-environnement, cycle hydro-social de l’eau,  mise en patrimoine de l’environnement, etc.
             </descriptif>
             <animateurs>
                 <nom_prenom>Klervi Fustec</nom_prenom>
                 <fonction>Géographie, Université de Polynésie Française
                 </fonction>
             </animateurs>
             <animateurs>
                 <nom_prenom>Emeline Hassenforder</nom_prenom>
                 <fonction>Sciences de l’eau, IRSTEA et Université Nationale d'Australie
                 </fonction>
             </animateurs>
        </evenement>
    </mois_annee>

=== tahalekhlaikh/projet_XML_LEKHLAIKH_M-BARKI/fevrier2020.xml
<?xml version ="1.0" ?>
<?xml-stylesheet type ="text/xsl" href ="evenements_par_mois.xsl" ?>

    <mois_annee mois="Février 2020" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="evenements_par_mois.xsd">
        <evenement jour="9">
             <icon>images/icon/conference_debat.jpg</icon>
             <type>Conférence débat</type>
             <titre>La RSE, une opportunité pour les entreprises africaines ?</titre>
             <date>Mardi 9 février 2020</date>
             <heure>17h30</heure>
             <lieu>Salle polyvalente</lieu>
             <organisateur>EMI-Indus</organisateur>
             <descriptif>Longtemps perçue comme une préocupation de pays riches ou l'apanage des multinationales, la responsabilité sociale et environnementale (RSE) suscite un intérêt croissant sur le continent africain. La RSE représente en effet une opportunité : celle de servir un développement durable et inclusif. Mais aussi, pour les entreprises, un levier de performance.
             </descriptif>
             <animateurs>
                 <nom_prenom>Alexandre Wong</nom_prenom>
                 <fonction>chercheur associé au CNRS  
                 </fonction>
             </animateurs>
             <animateurs>
                 <nom_prenom>Pierre Jacquemot</nom_prenom>
                 <fonction>Président du GRET
                 </fonction>
             </animateurs>
			 <animateurs>
                 <nom_prenom>Pierre Delcroix</nom_prenom>
                 <fonction>Directeur Ecologie Industrielle pour la région Afrique Moyen-Orient, Lafarge Holcim
                 </fonction>
             </animateurs>
			 <animateurs>
                 <nom_prenom>Jean-Baptiste Satchivi</nom_prenom>
                 <fonction> PDG du groupe CDPA-AGRISATCH-SBB
                 </fonction>
             </animateurs>
			 <animateurs>
                 <nom_prenom>Larissa Luy</nom_prenom>
                 <fonction>Experte Senior de l'IFC
                 </fonction>
             </animateurs>
        </evenement>
		<evenement jour="4">
             <icon>images/icon/Renfcap.jpg</icon>
             <type>Conférence – débat</type>
             <titre>Comment renforcer les acteurs porteurs de changement ?</titre>
             <date>Jeudi 4 février 2020</date>
             <heure>17h30</heure>
             <lieu>Salle polyvalente</lieu>
             <organisateur>EMI-Indus</organisateur>
             <descriptif>La période actuelle voit une prise de conscience de la nécessité de faire évoluer la manière de « penser » le renforcement des capacités. L’objectif est de renforcer la capacité d’une société à gérer ses propres affaires.
             </descriptif>
             <animateurs>
                 <nom_prenom>Benoit-Xavier Loridon</nom_prenom>
                 <fonction>directeur d’Initiative Développement, membre du F3E et du PRISME
                 </fonction>
             </animateurs>
             <animateurs>
                 <nom_prenom>Marie Hélène Nedelec</nom_prenom>
                 <fonction>vice-présidente de Nantes Métropole
                 </fonction>
             </animateurs>
			 <animateurs>
                 <nom_prenom>Daniel Neu</nom_prenom>
                 <fonction>chargé de programme « Département Politiques sociales et citoyenneté » au GRET
                 </fonction>
             </animateurs>
			 <animateurs>
                 <nom_prenom>Jean-Marc Pradelle</nom_prenom>
                 <fonction>chargé de mission à la Division « Appui au Renforcement des Capacités » à l’AFD
                 </fonction>
             </animateurs>
			 <animateurs>
                 <nom_prenom>Amadou Saley Oumarou</nom_prenom>
                 <fonction> haut-commissaire à la Modernisation de l’Etat du Niger
                 </fonction>
             </animateurs>
        </evenement>
		<evenement jour="2">
             <icon>images/icon/3e49d570.jpg</icon>
             <type>Rapport</type>
             <titre>le développement dans le monde 2016 : les dividendes du numérique </titre>
             <date>Mardi 2 février 2020</date>
             <heure>16h30</heure>
             <lieu>Salle polyvalente</lieu>
             <organisateur>EMI-Indus</organisateur>
             <descriptif>Les technologies numériques connaissent une expansion rapide presque partout, mais leurs dividendes — les avantages plus larges que procurent ces technologies  au plan du développement — tardent à se concrétiser. Souvent, elles dopent la croissance, élargissent les possibilités et améliorent la prestation des services. Pourtant, leur effet global n’a pas répondu aux attentes et est inégalement réparti. 
			 </descriptif>
             <animateurs>
                 <nom_prenom>Gaël Giraud</nom_prenom>
                 <fonction>AFD, chef économiste, directeur exécutif Etudes Recherches et Savoirs
                 </fonction>
             </animateurs>
             <animateurs>
                 <nom_prenom>Deepak Mishra</nom_prenom>
                 <fonction>Banque mondiale, Co-directeur du Rapport sur le développement dans le monde 2020
                 </fonction>
             </animateurs>
			 <animateurs>
                 <nom_prenom>Uwe Deichmann</nom_prenom>
                 <fonction>Banque mondiale, Co-directeur du Rapport sur le développement dans le monde 2020
                 </fonction>
             </animateurs>
        </evenement>

    </mois_annee>
