=== tahalekhlaikh/projet_XML_LEKHLAIKH_M-BARKI/evenements_club.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="evenements">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="organisateur"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="organisateur">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="detail"/>
        <xs:element maxOccurs="unbounded" ref="evenement"/>
      </xs:sequence>
      <xs:attributeGroup ref="attlist.organisateur"/>
    </xs:complexType>
  </xs:element>
  <xs:attributeGroup name="attlist.organisateur">
    <xs:attribute name="club" use="required"/>
  </xs:attributeGroup>
  <xs:element name="detail" type="xs:string"/>
  <xs:element name="evenement">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="icon"/>
        <xs:element ref="type"/>
        <xs:element ref="titre"/>
        <xs:element ref="date"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="icon" type="xs:string"/>
  <xs:element name="type" type="xs:string"/>
  <xs:element name="titre" type="xs:string"/>
  <xs:element name="date" type="xs:string"/>
</xs:schema>

=== tahalekhlaikh/projet_XML_LEKHLAIKH_M-BARKI/evenements_club.xml
<?xml version ="1.0" ?>
<?xml-stylesheet type ="text/xsl" href ="evenements_club.xsl" ?>

<evenements xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="evenements_club.xsd">
  
    
		
		<organisateur club="Club Emi Green">
		<detail>environnement.xml</detail>
           <evenement>
             <icon>images/icon/Nuage GIRE_15-1_th_128.jpg</icon>
             <type>Séminaire</type>
             <titre>Acteurs de l’eau et du climat : concilions nos agendas ! Séminaire 3 – L’influence des concepts et des instruments</titre>
             <date>Lundi 11 avril 2020</date>
          </evenement>		  
		</organisateur>

        <organisateur club="Club EMI-Economie">
    <detail>EmiEconomie.xml</detail>
        <evenement>
             <icon>images/icon/petrole_th_128.jpg</icon>
             <type>Conférence débat</type>
             <titre>Un pétrole à moins de 30$ le baril : quelles conséquences pour le développement ?</titre>
             <date>Mardi 12 avril 2020</date>
        </evenement>
        <evenement>
             <icon>images/icon/conference_debat.jpg</icon>
             <type>Conférence débat</type>
             <titre>La RSE, une opportunité pour les entreprises africaines ?</titre>
             <date>Mardi 9 février 2020</date>
        </evenement>
        <evenement>
             <icon>images/icon/Renfcap.jpg</icon>
             <type>Conférence débat</type>
             <titre>Comment renforcer les acteurs porteurs de changement ?</titre>
             <date>Jeudi 4 février 2020</date>
        </evenement>
        <evenement>
             <icon>images/icon/3e49d570.jpg</icon>
             <type>Rapport</type>
             <titre>le développement dans le monde 2020 : les dividendes du numérique</titre>
             <date>Mardi 2 février 2020</date>
        </evenement>        
    </organisateur>
		
		<organisateur club="Club Emi khayr">
		<detail>social.xml</detail>
            <evenement>
             <icon>images/icon/unicef-enfants_th_128.jpg</icon>
             <type>Séminaire</type>
             <titre>Genre et protection sociale</titre>
             <date>Mardi 8 Mars 2020</date>
             </evenement> 
            
		</organisateur>
		
		<organisateur club="Club EMI-Business">
		<detail>business.xml</detail>
           <evenement>
             <icon>images/icon/SOCIAL-BUSINESS-2-670x474.jpg</icon>
             <type>Conférence débat</type>
             <titre>Social business : comment changer d’échelle ?</titre>
             <date>Mardi 22 Mars 2020</date>
             </evenement> 
        </organisateur>
    
</evenements>
